name: CICD_Workflow
on: |
  - push
jobs:
  CODE_CHECKOUT:
    runs-on: self-hosted
    steps:
      - name: Code_Checkout
        uses: actions/checkout@v4

  BUILD:
    runs-on: self-hosted
    needs: CODE_CHECKOUT
    steps:
      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 

      - name: NPM Install 
        run: npm install   

      - name: Install HTML-Validate
        run: npm install --save-dev html-validate

      - name:    