name: CICD_Workflow
on: [push]
jobs:
  CODE_CHECKOUT:
    runs-on: ubuntu-latest
    steps:
      - name: Code_Checkout
        uses: actions/checkout@v4

  BUILD:
    runs-on: ubuntu-latest
    needs: CODE_CHECKOUT
    steps:
      - name: Code_Checkout
        uses: actions/checkout@v4

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 
       
      - name: verifying the node version and npm version
        working-directory: DevOps Project-1/Website
        run: |
          pwd
          node --version
          npm --version
          
          npm list html-validate

      - name: NPM Install 
        working-directory: DevOps Project-1/Website
        run: |
          npm install
          npm list html-validate  

      - name: Check html-validate version
        working-directory: DevOps Project-1/Website
        run: npm list html-validate    
         

      - name: HTML-Validator
        working-directory: DevOps Project-1/Website
        run: npx html-validate index.html
