name: CICD_Workflow
on: [push]
jobs:
  CLEAN_WORKSPACE:
    runs-on: self-hosted
    steps:
      - name: cleanup workspace 
        run: |
          rm -rf ./* ./.??* || true


  CODE_CHECKOUT:
    needs: CLEAN_WORKSPACE
    runs-on: self-hosted
    steps:
      - name: Code_Checkout
        uses: actions/checkout@v4

  BUILD:
    runs-on: self-hosted

    needs: CODE_CHECKOUT
    steps:
      - name: Code_Checkout
        uses: actions/checkout@v4

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' 
       
      - name: verifying the node version and npm version
        working-directory: DevOps Project-1/Website
        run: |
          pwd
          node --version
          npm --version
          
          npm list html-validate

      - name: NPM Install 
        working-directory: DevOps Project-1/Website
        run: |
          npm install
          npm list html-validate  

      - name: Check html-validate version
        working-directory: DevOps Project-1/Website
        run: npm list html-validate    
         

      - name: HTML-Validator
        continue-on-error: true
        working-directory: DevOps Project-1/Website
        run: npx html-validate index.html

      - name: PHS validator
        run: php -l "DevOps Project-1/Website/sendemail.php"  
  
  SONARQUBE_ANALYSIS:
    runs-on: self-hosted
    needs: BUILD
    steps:
      - name: Sonarqube Analysis
        run: |
          ls -l /opt/sonar-scanner/bin
          /opt/sonar-scanner/bin/sonar-scanner \
          -Dsonar.projectKey=static-web-application \
          -Dsonar.projectName=static-web-application \
          -Dsonar.sources=. \
          -Dsonar.host.url=${{ secrets.SONARQUBE_SERVER }} \
          -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
  DOCKER_BUILD:
    runs-on: self-hosted
    needs: SONARQUBE_ANALYSIS
    steps: 
      - name: Docker image build
        run: docker build -t static-website-image:${{github.run_number}} "DevOps Project-1/Website"

      - name: docker ps 
        run: docker images 
  Trivy_SCAN:
    runs-on: self-hosted
    needs: DOCKER_BUILD
    steps:
      - name: Trivy Scan
        run: |
          trivy image \
          --format table \
          --template "@contrib/html.tpl" \
          -o trivy-report.html \
          static-web-app:${{ github.run_number }}

      - name: upload artifact
        uses: actions/artifact-upload@v4
        with:
          name: trivy-report
          path: trivy-report.html
      
            

