name: CICD_Workflow
on: [push]
jobs:
  CLEAN_WORKSPACE:
    runs-on: self-hosted
    steps: rm -rf ./* ./.??* || true
  CODE_CHECKOUT:
    runs-on: ubuntu-latest
    steps:
      - name: Code_Checkout
        uses: actions/checkout@v4

  BUILD:
    needs: CLEAN_WORKSPACE
    runs-on: self-hosted
    needs: CODE_CHECKOUT
    steps:
      - name: Code_Checkout
        uses: actions/checkout@v4

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' 
       
      - name: verifying the node version and npm version
        working-directory: DevOps Project-1/Website
        run: |
          pwd
          node --version
          npm --version
          
          npm list html-validate

      - name: NPM Install 
        working-directory: DevOps Project-1/Website
        run: |
          npm install
          npm list html-validate  

      - name: Check html-validate version
        working-directory: DevOps Project-1/Website
        run: npm list html-validate    
         

      - name: HTML-Validator
        continue-on-error: true
        working-directory: DevOps Project-1/Website
        run: npx html-validate index.html

      - name: PHS validator
        run: php -l "DevOps Project-1/Website/sendemail.php"  
  
  DOCKER_BUILD:
    runs-on: self-hosted
    needs: BUILD
    steps:
      - name: Code_Checkout
        uses: actions/checkout@v4
      
      - name: install docker
        uses: docker/setup-docker-action@v5

      - name: Docker image build
        run: docker build -t static-website-image:latest "DevOps Project-1/Website"

      - name: docker ps 
        run: docker images 

